name: Cleanup PR Docs

on:
  pull_request:
    types: [closed]
    paths:
      - 'docs/**'
      - CHANGES.rst

jobs:
  cleanup-pr-docs:
    # Can only run with secrets on PRs from the same repository
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on:
      group: sofiagharunner
    steps:
      - name: Prepare SSH
        env:
          DEPLOY_KEY: ${{ secrets.GHA_RUNNER_PRIVATE_KEY }}
        run: |
          if [ -n "${DEPLOY_KEY}" ]; then
            echo "No secret for DEPLOY_KEY found"
            exit 1
          fi
          echo "${DEPLOY_KEY}" > id_rsa_deploy_key
          chmod 600 id_rsa_deploy_key
      - name: Cleanup PR docs via rsync
        env:
          DEPLOY_HOST: ${{ secrets.SOFIA_REDUX_DOC_HOST }}
          DEPLOY_USER: ${{ secrets.GHA_RUNNER_USER }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ -n "${DEPLOY_HOST}" ]; then
            echo "No secret for DEPLOY_HOST found"
            exit 1
          fi
          mkdir -p empty_dir
          rsync -avz --delete \
            -e "ssh -i id_rsa_deploy_key -o StrictHostKeyChecking=yes" \
            empty_dir/ "gha-runner@${DEPLOY_HOST}:pr-${PR_NUMBER}/"