name: Cleanup PR Docs

on:
  pull_request:
    types: [closed]
    paths:
      - 'docs/**'
      - CHANGES.rst

jobs:
  cleanup-pr-docs:
    # Can only run with secrets on PRs from the same repository
    if: github.event.pull_request.head.repo.fork == false
    runs-on:
      group: sofiagharunner
      labels: self-hosted
    steps:
      - name: Prepare SSH
        env:
          DEPLOY_KEY: ${{ secrets.GHA_RUNNER_PRIVATE_KEY }}
        run: |
          if [ -z "${DEPLOY_KEY}" ]; then
            echo "No secret for DEPLOY_KEY found"
            exit 1
          fi
          echo "${DEPLOY_KEY}" > id_rsa_deploy_key
          chmod 600 id_rsa_deploy_key
      - name: Cleanup PR docs via rsync
        env:
          DEPLOY_HOST: ${{ secrets.SOFIA_REDUX_DOC_HOST }}
          DEPLOY_USER: ${{ secrets.GHA_RUNNER_USER }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ -z "${DEPLOY_HOST}" ]; then
            echo "No secret for DEPLOY_HOST found"
            exit 1
          fi
          mkdir -p empty_dir
          rsync -avz --delete \
            -e "ssh -i id_rsa_deploy_key -o StrictHostKeyChecking=yes" \
            empty_dir/ "${DEPLOY_USER}@${DEPLOY_HOST}:pr-${PR_NUMBER}/"
      - name: Comment PR with docs URL
        if:  github.event.pull_request != null
        uses: actions/github-script@v7
        with:
          script: |
            const body = 
              "The PR has been closed, " +
              "so the preview documentation for it has been removed from the webserver." +
              "\n";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
