name: Build Documentation

on:
  push:
    branches:
      - sdc-dev
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install tox
        run: |
          pip install tox
      - name: Run tox to build docs
        run: |
          tox -e build-docs
      - name: Deploy documentation
        env:
          DEPLOY_KEY: ${{ secrets.GHA_RUNNER_PRIVATE_KEY }}
        run: |
          echo "Deploying documentation..."
          echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa_deploy_sdcwww
          chmod 600 ~/.ssh/id_rsa_deploy_sdcwww
          version="v$(python -c 'import sofia_redux; print(sofia_redux.__version__)')"
          mv docs/_build/html docs/_build/${version}
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_rsa_deploy_sdcwww -o StrictHostKeyChecking=yes" \
            "docs/_build/${version}/" "gha-runner@sdcwww.irs.uni-stuttgart.de:${version}/"

