# -*- coding: utf-8 -*-
# Licensed under a 3-clause BSD style license - see LICENSE.rst
#
# Astropy documentation build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this file.
#
# All configuration values have a default. Some values are defined in
# the global Astropy configuration which is loaded here before anything else.
# See astropy.sphinx.conf for which values are set there.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('..'))
# IMPORTANT: the above commented section was generated by sphinx-quickstart, but
# is *NOT* appropriate for astropy or Astropy affiliated packages. It is left
# commented out with this explanation to make it clear why this should not be
# done. If the sys.path entry above is added, when the astropy.sphinx.conf
# import occurs, it will import the *source* version of astropy instead of the
# version installed (if invoked as "make html" or directly with sphinx), or the
# version in the build directory (if "python setup.py build_sphinx" is used).
# Thus, any C-extensions that are needed to build the documentation will *not*
# be accessible, and the documentation will not build correctly.


# Disable some linter errors for this file
# ruff: noqa: F405 E501

import datetime
import sys
from pathlib import Path
from tomllib import load as toml_load

try:
    from sphinx_astropy.conf.v1 import *  # noqa
except ImportError:
    print('ERROR: the documentation requires the sphinx-astropy package to be installed')
    sys.exit(1)

# Get configuration information from pyproject.toml
with open(Path(__file__).parent.parent.parent.parent.parent
          / 'pyproject.toml', 'rb') as f:
    pyproject = toml_load(f)['project']

# -- General configuration ----------------------------------------------------

# By default, don't highlight syntax in literals
highlight_language = 'none'

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.2'

# To perform a Sphinx version check that needs to be more specific than
# major.minor, call `check_sphinx_version("x.y.z")` here.
# check_sphinx_version("1.2.1")

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns.append('_templates')

exclude_patterns.append('data_description.rst')
exclude_patterns.append('software_description.rst')
exclude_patterns.append('spectral_extraction.rst')
exclude_patterns.append('spectral_calibration.rst')

# This is added to the end of RST files - a good place to put substitutions to
# be used globally.
rst_epilog += """
"""

# -- Project information ------------------------------------------------------

# NASA document number and revision
docnumber = 'SDC-MAN-XXXX'
issue = '01'

# This does not *have* to match the package name, but typically does
project = pyproject['name']
author = pyproject['authors'][0]['name']
copyright = '{0}, {1}'.format(
    datetime.datetime.now().year, author)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

package = docnumber
version = 'Iss. %s' % issue
release = ': %s %s' % (package, version)


# -- Options for LaTeX output -------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto/manual]).
latex_documents = [('users',
                    'forcast_users.tex',
                    "FORCAST Redux User's Manual",
                    r"From Iss. 01: M. Wiedemann, A. Bryant, B. Greiner \and\large{Until Rev. M: M. Clarke, W. Vacca, E. Chambers, J. Radomski}",
                    'howto'),
                   ]

# Fix environment error, make one-sided document,
# add NASA header and footer
latex_elements = {
    'classoptions': ',openany,oneside',
    'babel': r'\usepackage[english]{babel}',
    'inputenc': r'\usepackage[utf8x]{inputenc}',
    'maxlistdepth': 20,
    'printindex': r'\footnotesize\raggedright\printindex',
    'preamble': r'''
\usepackage[section]{placeins}
\makeatletter
\AtBeginDocument{%%
  \@ifundefined{chapter}{}{%%
    \let\oldchapter\chapter
    \renewcommand{\chapter}{\FloatBarrier\oldchapter}%%
  }
  \let\oldpart\part
  \renewcommand{\part}{\FloatBarrier\oldpart}%%
  \let\oldsection\section
  \renewcommand{\section}{\FloatBarrier\oldsection}%%
  \let\oldsubsection\subsection
  \renewcommand{\subsection}{\FloatBarrier\oldsubsection}%%
  \let\oldsubsubsection\subsubsection
  \renewcommand{\subsubsection}{\FloatBarrier\oldsubsubsection}%%
}
\makeatother
\pagestyle{plain}
\setcounter{tocdepth}{2}
\usepackage{chngcntr}
\counterwithin{section}{part}
\counterwithin{subsection}{section}
\counterwithin{subsubsection}{subsection}
\renewcommand{\thepart}{\arabic{part}}
\renewcommand{\partname}{Part}
\renewcommand{\thesection}{\thepart.\arabic{section}}
\renewcommand{\thesubsection}{\thesection.\arabic{subsection}}
\renewcommand{\thesubsubsection}{\thesubsection.\arabic{subsubsection}}
\setcounter{secnumdepth}{3}
\makeatletter
\renewcommand{\l@section}{\@dottedtocline{1}{1.5em}{2.3em}}
\renewcommand{\l@subsection}{\@dottedtocline{2}{3.8em}{3.2em}}
\renewcommand{\l@subsubsection}{\@dottedtocline{3}{7.0em}{4.1em}}
\makeatother
\usepackage{fancyhdr}
\fancypagestyle{normal}{
\fancyhf{}
\fancyhead[R]{%s\\Iss. %s}
\fancyfoot[C]{\textbf{VERIFY THAT THIS IS THE CORRECT REVISION BEFORE USE}\\\thepage}
\setlength{\headheight}{22.36003pt}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}}
''' % (docnumber, issue),
}

# number figures for manuals
numfig = True
